- name: Rules for cloud.aws_ops to ensure the cloudtrail is encrypted
  hosts: all

  sources:
    - ansible.eda.aws_cloudtrail:
        region: 'us-east-1'
        delay_seconds: 5
  rules:
    - name: Enable Trail encryption
      condition: event.CloudTrailEvent.eventName=="UpdateTrail" and event.CloudTrailEvent.requestParameters.kmsKeyId=="" and event.CloudTrailEvent.requestParameters.name==vars.cloudtrail_name
      action:
         run_playbook:
           name: playbooks/eda/aws_restore_cloudtrail_encryption.yml

    - name: Re-create the CloudTrail
      condition: event.CloudTrailEvent.eventName=="DeleteTrail" and event.CloudTrailEvent.requestParameters.name==vars.cloudtrail_name
      action:
        run_playbook:
           name: playbooks/eda/aws_restore_cloudtrail.yml

    - name: Cancels the deletion of the KMS key and re-enables it
      condition: event.CloudTrailEvent.eventName=="ScheduleKeyDeletion" or event.CloudTrailEvent.eventName=="DisableKey"
      action:
        run_playbook:
           name: playbooks/eda/aws_restore_kms_key.yml
